language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

python:
  - 2.7.10

before_install:
  - sudo apt-get -qq update
  - pip install --user cpp-coveralls

script:
  - make && make test
after_success:
  - coveralls  --gcov-options '\-lp'
